"""Crear tabla mesa

Revision ID: 06650ae5571a
Revises: eac8fd855926
Create Date: 2026-07-02 19:42:50.893511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06650ae5571a'
down_revision: Union[str, Sequence[str], None] = 'eac8fd855926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesa',
    sa.Column('id_mesa', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_mesa'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_mesa_id_mesa'), 'mesa', ['id_mesa'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mesa_id_mesa'), table_name='mesa')
    op.drop_table('mesa')
    # ### end Alembic commands ###
