"""Crear tabla detalle pedido

Revision ID: 6fb8c23e0923
Revises: c6836fccc67b
Create Date: 2026-07-02 20:04:57.866402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb8c23e0923'
down_revision: Union[str, Sequence[str], None] = 'c6836fccc67b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_pedido',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_index(op.f('ix_detalle_pedido_id_detalle'), 'detalle_pedido', ['id_detalle'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_pedido_id_detalle'), table_name='detalle_pedido')
    op.drop_table('detalle_pedido')
    # ### end Alembic commands ###
